address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-ord5-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=pvdCOnObbHkQ7kNvwFWBlJk&_nc_oc=Adk4tT9QYd3s-PY4T7_WmO8qelv3Rk143UXbvHczx--ybFAIWbEnyFOvBO6RRYzQ_dI&_nc_zt=23&_nc_ht=scontent-ord5-1.xx&edm=AJdBtusEAAAA&_nc_gid=xssseYPkzOb_VG1BY_yZKQ&_nc_tpa=Q5bMBQHFCX5IgUoNca5RH7K-YqCzq2z82ZuJObojoD3KsAvnP-dSLD_MFUMTuY45TjfJ_Kw8SBmgDqDqRQ&oh=00_Afl2Xcy-ObDOOHF7QbfTXxpOHOeNkcot1Hj7sdty6RkJ3Q&oe=695A51AC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
