address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=XnllQbwBfQoQ7kNvwH-ZPIM&_nc_oc=Adn10aKPdSl2sHK6ya2PeuJt3m_R35J9gyV27GUhCge8zFawlzOMQ9roRI3WWvZuYsg&_nc_zt=23&_nc_ht=scontent-iad3-1.xx&edm=AJdBtusEAAAA&_nc_gid=nZXLAioMFcq5Ylv0r0JouA&_nc_tpa=Q5bMBQHKSWidvOcRcfmvIFLcwilMBrBJBeTjFY3XLo6k6g1FzHijyMx535TbcltLi74DdIySxz8KeLw9ag&oh=00_AfqjcRS1T7m5VUnYGdEZBkz_1TmBxHOD1SKyk3rAkLklug&oe=69638C2C
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
