address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=qDgijEhFCkQQ7kNvwG9FEjZ&_nc_oc=AdnWe6-x1o3Ngytl5e8dacQo99YEVU8NY9W9ZePTjr2qWFUmYLbbiMZbU3H8BCXCVzY&_nc_zt=23&_nc_ht=scontent-iad3-1.xx&edm=AJdBtusEAAAA&_nc_gid=L305x6BzhgudeA_8migN8A&_nc_tpa=Q5bMBQFcLYWHpWNtL3V-NY0rYcFt1Y8YPUCBChVhrGD_O2EbExr78TOd8FMOGoQTmraqbXGmDHdz8eeeBA&oh=00_Afvo8G_sXQ33QGeS9wJOPSpNQGZWjjCUUZ9HNG0b4Feh2Q&oe=698724AC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
