address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-sjc6-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=Y5abPLEw3KgQ7kNvwH9rWIK&_nc_oc=AdlEUVJxZzIyaDJ06nUmzs3dLAOBcqH6Eo-S_IY8GrhrRDCb7MyzbF09r71snHSgRAU&_nc_zt=23&_nc_ht=scontent-sjc6-1.xx&edm=AJdBtusEAAAA&_nc_gid=M1vR_vAVyfIKx3a7Dxz2xg&_nc_tpa=Q5bMBQHyv_sH8jkqJG3GhmQYxzGMQeTVuB4PJEl-xCgbvOt2o5fFM59UVDRCgFnDjXtZ2_SdrtmVuyfEUA&oh=00_Afnh1W0Hzuq805HQbmt-_3FnsV0zAp-16DgVQDdy5d7c5Q&oe=693FF3AC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
