address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=aI22gfMw2b4Q7kNvwG85XfU&_nc_oc=AdkSjrPQUqtcC3rWb8Dw_pI4e9DkC7HHaDrQH8fjum9Z36XGJ0eQiaOKzqDban3lOUQ&_nc_zt=23&_nc_ht=scontent-iad3-1.xx&edm=AJdBtusEAAAA&_nc_gid=r_txIOItiysq6C3X5WLYVg&_nc_tpa=Q5bMBQEKWxxbwFDHHRxAkBT5-h57bOMCNy1n9GmJXg69pIrrcPc6X_7yEMPd_5b1rRZ2Ihh0LTG2aZKieA&oh=00_AfoA5xG970LDI-mqulzG7j4cpGzRzCHB94-rHhnGnE8kAw&oe=696E182C
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
