address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-sjc6-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=GmIK0rlH2qwQ7kNvwEKjWFS&_nc_oc=AdkMlNA6teLJNlo6cp4nJ5NPi5vNbza5eTomiz80REgXE3EZ7pc3aEdTSsgTOf-jCCc&_nc_zt=23&_nc_ht=scontent-sjc6-1.xx&edm=AJdBtusEAAAA&_nc_gid=83UN_NSUc9tPUshV7a-_dA&_nc_tpa=Q5bMBQGn042QvVMDgi_Nx4-vG_Vs9fUPKMa6CT6_PrX8essnonkJ10tS15rDsjgYwFVCspLoUsxcv1iwcg&oh=00_AfhFRzSkM91hl7hXDicyD9zzBY_CTPnb4VQ3w4hrJ9vlhw&oe=690DDAAC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
