address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-sjc6-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=hIWe3VfXXd4Q7kNvwHEn256&_nc_oc=Adk-3Dn61jnBZA3y78EV7CPn_wfRfFTTqsqBkj8nYL4Lkeu1Or4PVx_EpLAP2OYp9Lw&_nc_zt=23&_nc_ht=scontent-sjc6-1.xx&edm=AJdBtusEAAAA&_nc_gid=hVjzamiBP5dtKzrHs1TzEQ&_nc_tpa=Q5bMBQElYGziI8uiIrUodUPL3tI0JYOVC3vY2HtT8nn6zDuzFWGCN8l6t55WNxNP8JrwXsFLth3sn7f8JQ&oh=00_AfldeFxyCyDo_MR6628m163_OdH_UXLutGnegrXI3lSzlQ&oe=694A7FAC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
