address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-atl3-2.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=pvdCOnObbHkQ7kNvwHQ4gAL&_nc_oc=AdlYHfaPJfQ87V7h142AUdDWzSnuQyKmCLQF3iOas75Tz2VGXye0SxpJ1uZu4NH8EwU&_nc_zt=23&_nc_ht=scontent-atl3-2.xx&edm=AJdBtusEAAAA&_nc_gid=j4UueN0LliCNsP0niTNboA&_nc_tpa=Q5bMBQED1L2zNoRrDE56fQ9GSbr360cDriEwcSfvIOuL5dw1ZKnZgNozi84trs24c97Tw6qEMAut1Xe30w&oh=00_Afn8TpGiaTGa5uzK-CDCI_JKZXyA5n38mEQDKJgGt9Mbzg&oe=6957AEAC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
