address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-ams2-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=WWaNz431u90Q7kNvwEqowR5&_nc_oc=AdnjZYvij5XtJKo09vKDZZkSxBN9-FAzsnGjFV3JZXRT6rzdjkybaCpoAnlaWdZIx3Y&_nc_zt=23&_nc_ht=scontent-ams2-1.xx&edm=AJdBtusEAAAA&_nc_gid=JFY7MOIQyY4McsV5RGs-cQ&_nc_tpa=Q5bMBQFi-5tsvPwg8JQwjgXqwY3PlPVNEjc1hmyPPuESBNSh8zAM6oF1hlLESKt48Qj4uy6H4BjbP58Aog&oh=00_Afojz77RCjexX5vrLsSwBnJtf5S1x2rv3Gv1d8oHdxvLRA&oe=695BA32C
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
