address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-ord5-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=351699&_nc_ohc=hP7jvG6lR7EQ7kNvwEiW71i&_nc_oc=AdkvaC3O_7lNWlATHjDvm4SMBr9rFcb2kTzl6SiKjz20eea_eN2eugixrYAqAdunoCE&_nc_zt=23&_nc_ht=scontent-ord5-1.xx&edm=AJdBtusEAAAA&_nc_gid=BYp3lizwiqWZBNRTIYqHlQ&_nc_tpa=Q5bMBQGG2wA0ZEXA5eP4ReJYojB9-M-uTj_bQ-se5olrC2GoqWDgIm9MGcc3Y0YOGT6bgFG3aGUwPw1Q6A&oh=00_AfusSJ7YuspTWu481SQqWKEXY8N6Vrd1Es_xcSScdA4jkw&oe=699C3CAC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
