address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-sjc6-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=351699&_nc_ohc=f-lypxkPs6cQ7kNvwE5h6ZY&_nc_oc=Adm9RIWQj8i0_z30B8ZlGxiZnGm_am7gi9i-VLMfGZSWBNT4j1TUN5W4V1mpWVTn4kM&_nc_zt=23&_nc_ht=scontent-sjc6-1.xx&edm=AJdBtusEAAAA&_nc_gid=ImMnt5xJwYuj3JTb8HggHA&_nc_tpa=Q5bMBQFGHQD4cuMKMbYIB5II-XxIJaZ8iFojgFoYbsNXO6BlFCW3FKr5ovUASyvGqdvFCVRwHBdswkpBdg&oh=00_AfuHdJLiYpz7sfGeygH0PXsRYLTYmcsHNDB0LUSZyjzOeg&oe=69A6C8AC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
