address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-sjc6-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=JMvWYgG2jagQ7kNvwEuLpOB&_nc_oc=Adl_qaVxCuo78gXHebcm4BC1WViENXw9jD31_0YcDfq_hAp4oZ1NSelIjFx5VpFM3-w&_nc_zt=23&_nc_ht=scontent-sjc6-1.xx&edm=AJdBtusEAAAA&_nc_gid=FpowzTJ_7Xdjq-bcCXYXdw&_nc_tpa=Q5bMBQF7jRgVPZpE-gQjvj4d8FWDWdCHjffevRtddtFu3eh9EzI09GlGKImy9JPRkX6XsHjuU3YNUXviRg&oh=00_Aft7_3VvKfsOvRf4dUdlbtwtfq-TfzRlStraFmuSQtWpWg&oe=698C6AAC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
