address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-ams2-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=WrJm0qXfSDsQ7kNvwH2RPqT&_nc_oc=AdlQ25ozdvSt4lVLxSLTWSx5R7jgj_SyHUUc53dgd9M1i6FdXEN20nhYeT-nXliS20I&_nc_zt=23&_nc_ht=scontent-ams2-1.xx&edm=AJdBtusEAAAA&_nc_gid=A4MCVbnHIrt1NClEEYjiUA&_nc_tpa=Q5bMBQHP6TcFskCVHtWutprONEir1XlhI35rj6BPsoFH-DwqYD-ytG6EGXEafuBCIwcJXr0a-t__Doh3hQ&oh=00_AfvN23ICe7Gt5oai4qym96r7nAnIvqsW5Gb3D3uHlY-6IQ&oe=698481AC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
