address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-ams2-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=dc4938&_nc_ohc=GAL7GxEaeFkQ7kNvwGpVdXw&_nc_oc=AdkZ_pNFaMPy8yzxoTNN31wsMEGltkri9kfIAxzapOg0zCvFL3BZTbVBA7XGbVv6ahw&_nc_zt=23&_nc_ht=scontent-ams2-1.xx&edm=AJdBtusEAAAA&_nc_gid=cmC_pYtL0b3sLagiTrDh-Q&_nc_tpa=Q5bMBQHYf6RU9118thVtZ-36T1u3kmEFKLC3e4tqUPjGDGLo8RmNujxSP8juQ6uuwjOs4NAZ8Pa1YSy0Fw&oh=00_AfmjOkaMXkOcazoyctad-KDJcfWq981jI01L5_NgZ1pLBg&oe=693567AC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
